apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: YXRhYmFzZS0xLmNjdms2ZTYyaXo4aC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  db_username: YWRtaW4=
  db_password: Q2xvdWQxMjM=
